"""모델 진단 스크립트

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bg9zP65ijziqjWugtJLA7aKs8UCEtCFf
"""

import os
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
import numpy as np  # npz 파일을 읽기 위해 numpy 추가
from src.models.motion_model import RiskConditionedModel
import bisect

def calculate_ade_fde(model, dataloader, device):
    """
    데이터 로더를 순회하며 K개 모드(궤적 후보)를 반환하는 다중 모드 모델의
    minADE / minFDE 성능을 계산합니다. (낮을수록 좋은 모델입니다.)
    모델 출력 형태: [B, K=6, T=80, 2]
    """
    model.eval() # 모델을 평가 모드로 전환 (Dropout, BatchNorm 비활성화)
    total_ade = 0.0
    total_fde = 0.0
    total_samples = 0
    valid_fde_samples = 0

    with torch.no_grad(): # 평가 시에는 기울기(gradient) 계산을 비활성화하여 메모리 절약
        for inputs, targets in dataloader:

            # 1. 딕셔너리 형태의 입력 데이터를 모두 device(GPU/CPU)로 이동
            inputs = {k: v.to(device) for k, v in inputs.items()}

            # targets 추출 및 device 이동
            gt_trajs = targets['gt_trajs'].to(device)    # [B, T=80, 2 (x,y)]
            gt_valids = targets['gt_valids'].to(device)  # [B, T=80] (1.0 or 0.0)

            # 2. 모델 예측 - 다중 모드 출력 [B, K=6, T=80, 2]
            pred_trajs = model(inputs)

            # 예측값과 정답값의 x, y 좌표. gt는 K 차원으로 브로드캐스트하기 위해 unsqueeze.
            pred_xy = pred_trajs[..., :2]                  # [B, K, T, 2]
            gt_xy = gt_trajs[..., :2].unsqueeze(1)         # [B, 1, T, 2]

            # 3. 각 모드·타임스텝 별 L2 거리(유클리디안 거리) 계산
            # shape: [B, K, T]
            l2_distances = torch.norm(pred_xy - gt_xy, dim=-1)

            # --- minADE (K개 모드 중 최소 ADE) 계산 ---
            # 유효한(valid) 타임스텝의 거리만 남기기 위해 mask 곱셈 (K로 브로드캐스트)
            masked_l2 = l2_distances * gt_valids.unsqueeze(1)   # [B, K, T]

            # 각 배치(시나리오)마다 유효한 스텝의 개수 계산
            valid_steps_per_sample = gt_valids.sum(dim=1)
            # 0으로 나누는 것을 방지하기 위해 최소값을 1로 설정
            valid_steps_per_sample = torch.clamp(valid_steps_per_sample, min=1.0)

            # 모드별 평균 거리 [B, K] -> 모드 차원에서 최솟값을 취해 샘플당 minADE [B]
            sample_ade = (masked_l2.sum(dim=-1) / valid_steps_per_sample.unsqueeze(1)).min(dim=1).values
            total_ade += sample_ade.sum().item()
            total_samples += gt_trajs.size(0)

            # --- minFDE (K개 모드 중 최소 FDE) 계산 ---
            # 궤적의 맨 마지막 스텝([-1]) 기준 거리. 모드별로 남겨두고 마지막에 min.
            final_distances = l2_distances[:, :, -1]   # [B, K]
            final_valids = gt_valids[:, -1]             # [B]

            # 마지막 스텝이 유효한(valid == 1.0) 데이터만 FDE 계산에 포함
            total_fde += (final_distances.min(dim=1).values * final_valids).sum().item()
            valid_fde_samples += final_valids.sum().item()

    # 데이터가 아예 없는 경우 예외 처리
    if total_samples == 0:
        return 0.0, 0.0

    # 전체 데이터에 대한 평균 계산
    mean_ade = total_ade / total_samples

    # FDE는 마지막 스텝이 유효했던 샘플들로만 평균을 냅니다.
    mean_fde = total_fde / valid_fde_samples if valid_fde_samples > 0 else 0.0

    # 평가는 다시 학습을 위해 모델 모드를 원래대로 돌려놓는 것이 좋지만,
    # 보통 train 루프 바깥에서 model.train()을 다시 호출합니다.
    return mean_ade, mean_fde

def diagnose_model(model, train_loader, val_loader, device=None, overfit_gap=1.0):
    """
    학습된 모델의 상태를 진단하여 언더피팅/오버피팅 여부를 판별합니다.
    """
    if device is None:
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    model = model.to(device)

    # 1. 평가 모드 전환 (드롭아웃, 배치 정규화 등 비활성화)
    model.eval()

    print(f"[{device}] 장치에서 성능 평가를 시작합니다...")

    # 2. 기울기 계산 비활성화 (메모리 절약 및 속도 향상)
    with torch.no_grad():
        train_ade, train_fde = calculate_ade_fde(model, train_loader, device)
        val_ade, val_fde = calculate_ade_fde(model, val_loader, device)

    print("-" * 50)
    print(f"Train ADE: {train_ade:.2f}, Val ADE: {val_ade:.2f}")
    print(f"Train FDE: {train_fde:.2f}, Val FDE: {val_fde:.2f}")
    print("-" * 50)

    # 3. 진단 조건문
    # ADE는 오차 지표이므로 낮을수록 좋음.
    # 오버피팅: 학습 오차는 낮은데 검증 오차가 큼 -> (val - train)이 큼
    gap = val_ade - train_ade

    # K=6 다중 모드 기준 minADE는 보통 0.5~1.5m(잘 학습), >3m면 학습이 부족.
    # (단일 모드 ADE보다 더 낮은 값이 정상이므로 임계값도 단일 ADE 기준보다 작게 설정)
    if train_ade > 3.0:
        # 학습 데이터조차 제대로 못 맞추면(=학습 오차가 큼) 무조건 언더피팅
        print("진단: 언더피팅 (과소적합) - 모델 수용력을 키우거나 학습을 더 진행하세요.")

    elif gap > overfit_gap:
        # 학습은 잘했는데 평가 성능과 차이가 크면 오버피팅
        print("진단: 오버피팅 (과적합) - 강력한 규제(드롭아웃, 데이터 증강)가 필요합니다.")

    else:
        # 학습도 잘했고 격차도 적으면 일반화 성공
        print("진단: 일반화 성공 - 훌륭한 모델입니다!")

# 테스트를 위한 실행 코드
if __name__ == "__main__":
    # 1. 지정된 경로에서 npz 데이터를 불러오는 커스텀 Dataset 정의
    class WaymoCacheDataset(Dataset):
        def __init__(self, cache_dir):
            self.cache_dir = cache_dir
            self.cumulative_sizes = []

            if os.path.exists(cache_dir):
                # 해당 폴더 내의 .npz 파일들만 리스트업 (재현성을 위해 정렬)
                self.file_list = sorted(
                    f for f in os.listdir(cache_dir)
                    if f.endswith('.npz') and os.path.isfile(os.path.join(cache_dir, f))
                )
                print(f"[{cache_dir}] 경로에서 {len(self.file_list)}개의 .npz 데이터 파일을 찾았습니다.")
                total_scenarios = 0
                for f in self.file_list:
                    # mmap_mode='r'을 사용하여 파일을 메모리에 전부 올리지 않고 메타데이터(shape)만 빠르게 읽습니다.
                    # with 블록으로 핸들을 즉시 해제하여 자원 누수 방지.
                    with np.load(os.path.join(cache_dir, f), mmap_mode='r') as data:
                        num_scenarios = data["agents"].shape[0] # 해당 파일 내의 시나리오(배치) 개수
                    total_scenarios += num_scenarios
                    self.cumulative_sizes.append(total_scenarios)
            else:
                print(f"경고: {cache_dir} 경로를 찾을 수 없습니다. 폴더가 존재하는지 확인해주세요.")
                self.file_list = []

        def __len__(self):
            if not self.cumulative_sizes:
                return 0
            return self.cumulative_sizes[-1]

        def __getitem__(self, idx):
            if not self.file_list:
                raise IndexError("데이터셋이 비어있습니다.")

            # 1. 요청된 전역 idx가 어느 파일에 속하는지 이진 탐색(bisect)으로 빠르게 찾기
            file_idx = bisect.bisect_right(self.cumulative_sizes, idx)

            # 2. 해당 파일 내에서의 로컬 인덱스(local_idx) 계산
            if file_idx == 0:
                local_idx = idx
            else:
                local_idx = idx - self.cumulative_sizes[file_idx - 1]

            file_path = os.path.join(self.cache_dir, self.file_list[file_idx])

            # 3. npz 파일 로드
            data = np.load(file_path, allow_pickle=True)

            try:
                # 4. 파일에서 [local_idx]에 해당하는 '단일 시나리오'만 추출
                agent = data['agents'][local_idx]
                scene = data['scenes'][local_idx]
                traf = data['trafs'][local_idx]
                gt_trajs = data['gt_trajs'][local_idx]
                gt_valids = data['gt_valids'][local_idx]
                risk_label = data['risk_labels'][local_idx]
            except KeyError:
                print(f"\n[오류] {file_path} 파일에 지정한 키가 없습니다. 존재하는 키: {data.files}")
                raise

            # 5. numpy 배열을 PyTorch Tensor로 변환 및 차원(Shape) 맞추기
            # 주의: 모델 입력 shape에 표시된 선두 차원 '1'은 배치 차원이며 DataLoader가 자동으로 추가한다.
            # 따라서 Dataset은 한 샘플 분량만 반환해야 하므로 .unsqueeze(0)는 사용하지 않는다.
            # map_scene은 데이터의 마지막 피처 8개 중 모델이 요구하는 앞 6개만 슬라이싱.
            inputs = {
                "ego_hist": torch.tensor(agent[0], dtype=torch.float32),       # [11, 10] -> 배치 후 [B, 11, 10]
                "social": torch.tensor(agent[1:], dtype=torch.float32),         # [31, 11, 10] -> [B, 31, 11, 10]
                "map_scene": torch.tensor(scene[..., :6], dtype=torch.float32), # [50, 10, 6] -> [B, 50, 10, 6]
                "traf_t": torch.tensor(traf, dtype=torch.float32),              # [6, 1] -> [B, 6, 1]
                "risk_label": torch.tensor(risk_label, dtype=torch.float32)     # [3] -> [B, 3]
            }

            targets = {
                "gt_trajs": torch.tensor(gt_trajs, dtype=torch.float32),
                "gt_valids": torch.tensor(gt_valids, dtype=torch.float32),
            }

            return inputs, targets


    # 3. 데이터 로더 생성 (요청하신 Waymo Trajectory 캐시 경로 반영)
    train_dir = "/home/dtlab/gy/waymo_traj/waymo_traj/cache/train"
    val_dir = "/home/dtlab/gy/waymo_traj/waymo_traj/cache/val"

    train_dataset = WaymoCacheDataset(train_dir)
    val_dataset = WaymoCacheDataset(val_dir)

    # 궤적(Trajectory) 데이터처럼 순서나 셔플이 중요한 경우 옵션을 조정하세요.
    train_loader = DataLoader(train_dataset, batch_size=16, shuffle=False)
    val_loader = DataLoader(val_dataset, batch_size=16, shuffle=False)

    # 4. 모델 인스턴스화 및 진단 함수 호출
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = RiskConditionedModel(d_model=128, K=6, n_layers=2,
                                     map_dim=8,
                                     use_lane_mamba=True,
                                     use_risk_prefix=True,
                                     use_traj_fix=True,
                                     use_map_per_step=False,
                                     use_ar=False,
                                     use_lane_anchor=False,
                                     cond_dim=3).to(device)

    # 오버피팅 판단 격차 1.0m (minADE 단위; K=6 기준 0.5~1m 차이도 유의미)
    diagnose_model(model, train_loader, val_loader, device=device, overfit_gap=1.0)